In [ ]:
# Step 1: Import necessary libraries.
from sklearn import preprocessing
from sklearn.naive_bayes import GaussianNB, MultinomialNB

In [ ]:
# Step 2: Prepare dataset.
weather = ['Sunny', 'Sunny', 'Overcast', 'Rainy', 'Rainy','Rainy', 'Overcast','Sunny', 'Sunny', 'Rainy', 'Sunny', 'Overcast', 'Overcast', 'Rainy']
temp = ['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild','Cool','Mild','Mild','Mild','Hot','Mild']
play=['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','Yes','No']

In [ ]:
# Step 3: Digitize the data set using encoding

#creating labelEncoder
le = preprocessing.LabelEncoder()

# Converting string labels into numbers.
weather_encoded=le.fit_transform(weather)
temp_encoded=le.fit_transform(temp)
label=le.fit_transform(play)
print("Weather:" ,weather_encoded)
print("Temp:",temp_encoded)
print("Play:",label)

Weather: [2 2 0 1 1 1 0 2 2 1 2 0 0 1]
Temp: [1 1 1 2 0 0 0 2 0 2 2 2 1 2]
Play: [0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [ ]:
# Step 4: Merge different features to prepare dataset

#Combinig weather and temp into single listof tuples
features=tuple(zip(weather_encoded,temp_encoded))
print("Features:",features)


Features: ((2, 1), (2, 1), (0, 1), (1, 2), (1, 0), (1, 0), (0, 0), (2, 2), (2, 0), (1, 2), (2, 2), (0, 2), (0, 1), (1, 2))


In [ ]:
#Create a Classifier
model=MultinomialNB()
# Train the model using the training sets
model.fit(features,label)

MultinomialNB()

In [ ]:
# Step 6: Predict Output for new data

predicted= model.predict([[2,2]]) # 0:Overcast, 2:Mild
print("Predicted Value:", predicted)

Predicted Value: [1]


### **EXCERCISE**

In [ ]:
# (1) Will you play if the temperature is ‘Hot’ and weather is ‘overcast’?
predicted= model.predict([[0,1]]) # 0:Overcast, 1:Hot
print("Predicted Value:", predicted)

Predicted Value: [1]


In [ ]:
# (2) Will you play if the temperature is ‘Mild’ and weather is ‘Sunny’?
predicted= model.predict([[2,2]]) # 2:Sunny, 2:Mild
print("Predicted Value:", predicted)

Predicted Value: [1]


Task : 1 :- Try the algo on Dataset3 - OneHotEncoding of features and Train test Division 85%-15%

Questions: For Task - 1

(1) What will be the value of Play, if Outlook is ’Rainy’, Temperature is ’Mild’, Humidity =’Nor-
mal’, and Wind = ’False’?

(2) What will be the value of Play, if Outlook is ’Sunny’, Temeprature is ’Cool’, Humidity =’High’,
and Wind = ’True’?

(3) Accuracy , precision and recall of both Models?

In [ ]:
#Import scikit-learn dataset library
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB
import pandas as pd
from sklearn import preprocessing

In [ ]:
datasets = pd.read_csv('/content/drive/MyDrive/SEM_^/ML/Lab-03/Dataset3.csv')
datasets

Outlook Temp Wind  Humidity  Class
0        R    H    F         1      0
1        R    H    T         2      0
2        O    H    F         1      1
3        R    M    F         1      1
4        S    C    F         1      1
5        O    C    T         0      0
6        O    C    T         1      1
7        R    M    F         1      0
8        O    C    F         0      1
9        S    M    F         2      1
10       R    C    T         2      0
11       O    M    T         0      1
12       O    H    F         1      1
13       S    M    T         1      0

In [ ]:
from sklearn.preprocessing import OneHotEncoder

le = preprocessing.OneHotEncoder()
Out_train = datasets.select_dtypes('object')
Temp_train = datasets.select_dtypes('object')
Wind_train = datasets.select_dtypes('object')

out_end = le.fit_transform(Out_train).toarray()
Temp_end = le.fit_transform(Temp_train).toarray()
wind_end = le.fit_transform(Wind_train).toarray()

train = pd.DataFrame(out_end,columns=le.get_feature_names_out(Out_train.columns))
# print(train)
train = pd.DataFrame(out_end,columns=le.get_feature_names_out(Out_train.columns))
train = pd.DataFrame(out_end,columns=le.get_feature_names_out(Out_train.columns))
print(train)
# print(datasets)
# df = pd.merge(train,datasets)
datasets = pd.DataFrame.join(datasets,train)
# print(datasets)
# datasets['Outlook'] = datasets['Outlook'].astype('category')
# datasets['Temp'] = datasets['Outlook'].astype('category')
# datasets['Wind'] = datasets['Outlook'].astype('category')

# datasets['Outlook_new'] = datasets['Outlook'].cat.codes
# datasets['Temp_new'] = datasets['Outlook'].cat.codes
# datasets['Wind_new'] = datasets['Outlook'].cat.codes

# enc_data = pd.DataFrame(le.fit_transform(datasets[['Outlook_new','Temp_new','Wind_new']]).toarray())
# one_hot_encoded_data = pd.get_dummies(datasets, columns = ['Outlook','Temp','Wind'])
datasets.drop(['Outlook', 'Temp','Wind'], axis=1, inplace=True)
print(datasets)
# datasets
# new_df = datasets.join(enc_data)
# one_hot_encoded_data


    Outlook_O  Outlook_R  Outlook_S  Temp_C  Temp_H  Temp_M  Wind_F  Wind_T
0         0.0        1.0        0.0     0.0     1.0     0.0     1.0     0.0
1         0.0        1.0        0.0     0.0     1.0     0.0     0.0     1.0
2         1.0        0.0        0.0     0.0     1.0     0.0     1.0     0.0
3         0.0        1.0        0.0     0.0     0.0     1.0     1.0     0.0
4         0.0        0.0        1.0     1.0     0.0     0.0     1.0     0.0
5         1.0        0.0        0.0     1.0     0.0     0.0     0.0     1.0
6         1.0        0.0        0.0     1.0     0.0     0.0     0.0     1.0
7         0.0        1.0        0.0     0.0     0.0     1.0     1.0     0.0
8         1.0        0.0        0.0     1.0     0.0     0.0     1.0     0.0
9         0.0        0.0        1.0     0.0     0.0     1.0     1.0     0.0
10        0.0        1.0        0.0     1.0     0.0     0.0     0.0     1.0
11        1.0        0.0        0.0     0.0     0.0     1.0     0.0     1.0
12        1.

In [ ]:
features = datasets.iloc[:,0:9].values
features[:,0] = datasets.iloc[:,0].values
features[:,1] = datasets.iloc[:,2].values
features[:,1] = datasets.iloc[:,3].values
features[:,1] = datasets.iloc[:,4].values
features[:,1] = datasets.iloc[:,5].values
features[:,1] = datasets.iloc[:,6].values
features[:,1] = datasets.iloc[:,7].values
features[:,1] = datasets.iloc[:,8].values
features[:,1] = datasets.iloc[:,9].values
# features[:,1] = datasets.iloc[:,2].values
features

array([[1., 0., 0., 1., 0., 0., 1., 0., 1.],
       [2., 1., 0., 1., 0., 0., 1., 0., 0.],
       [1., 0., 1., 0., 0., 0., 1., 0., 1.],
       [1., 0., 0., 1., 0., 0., 0., 1., 1.],
       [1., 0., 0., 0., 1., 1., 0., 0., 1.],
       [0., 1., 1., 0., 0., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 1., 0., 0., 0., 1., 1.],
       [0., 0., 1., 0., 0., 1., 0., 0., 1.],
       [2., 0., 0., 0., 1., 0., 0., 1., 1.],
       [2., 1., 0., 1., 0., 1., 0., 0., 0.],
       [0., 1., 1., 0., 0., 0., 0., 1., 0.],
       [1., 0., 1., 0., 0., 0., 1., 0., 1.],
       [1., 1., 0., 0., 1., 0., 0., 1., 0.]])

In [ ]:
label = datasets.iloc[:,1].values
label

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0])

In [ ]:
#import the necessary module
from sklearn.model_selection import train_test_split
#split data set into train and test sets
data_train, data_test, target_train, target_test = train_test_split(features,label, test_size = 0.15, random_state = 114)
print("Traing data : \n",data_train)
print("\nTesting data : \n",data_test)
print("\nTarget train : \n",target_train)
print("\nTarget test : \n",target_test)

Traing data : 
 [[1. 0. 0. 0. 1. 1. 0. 0. 1.]
 [1. 0. 0. 1. 0. 0. 1. 0. 1.]
 [1. 0. 1. 0. 0. 0. 1. 0. 1.]
 [0. 1. 1. 0. 0. 0. 0. 1. 0.]
 [2. 1. 0. 1. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 1. 0. 0. 1.]
 [1. 1. 0. 0. 1. 0. 0. 1. 0.]
 [1. 0. 1. 0. 0. 0. 1. 0. 1.]
 [1. 1. 1. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 1. 0. 0. 0. 1. 1.]
 [2. 1. 0. 1. 0. 1. 0. 0. 0.]]

Testing data : 
 [[1. 0. 0. 1. 0. 0. 0. 1. 1.]
 [0. 1. 1. 0. 0. 1. 0. 0. 0.]
 [2. 0. 0. 0. 1. 0. 0. 1. 1.]]

Target train : 
 [1 0 1 1 0 1 0 1 1 1 0]

Target test : 
 [0 0 1]


In [ ]:
import numpy as np
gnb = GaussianNB()

#Train the model using the training sets
gnb.fit(data_train, target_train)

#Predict the response for test dataset
target_pred = gnb.predict(data_test)
target_pred

array([0, 1, 0])

In [ ]:
# (1) What will be the value of Play, if Outlook is ’Rainy’, Temperature is ’Mild’, Humidity =’Nor-
# mal’, and Wind = ’False’?
predicted = gnb.predict([[1,0,1,0,0,0,1,1,0]])
predicted

array([1])

In [ ]:
# (2) What will be the value of Play, if Outlook is ’Sunny’, Temeprature is ’Cool’, Humidity =’High’,
# and Wind = ’True’?

predicted = gnb.predict([[2,0,0,1,1,0,0,0,1]])
predicted

array([0])

In [ ]:
# (3) Accuracy , precision and recall of both Models?

#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))

Accuracy: 0.3333333333333333


In [ ]:
#Import confusion_matrix from scikit-learn metrics module for confusion_matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test, target_pred)

array([[1, 1],
       [1, 0]])

In [ ]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
precision = precision_score(target_test, target_pred, average=None)
recall = recall_score(target_test, target_pred, average=None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [0.5 0. ]
recall: [0.5 0. ]


Task 2: Try the algo on Wine datasets - OneHotEncoding of features:and Train test Division 85%-15%

In [ ]:
from sklearn import datasets

wine = datasets.load_wine()
X = wine.data
y= wine.target

In [ ]:
feature_names = wine.feature_names
target_names = wine.target_names
print("Feature names:", feature_names)
print()
print("Target names:", target_names)
print()
print("\nFirst 10 rows of X:\n", X[:10])

Feature names: ['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']

Target names: ['class_0' 'class_1' 'class_2']


First 10 rows of X:
 [[1.423e+01 1.710e+00 2.430e+00 1.560e+01 1.270e+02 2.800e+00 3.060e+00
  2.800e-01 2.290e+00 5.640e+00 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 1.120e+01 1.000e+02 2.650e+00 2.760e+00
  2.600e-01 1.280e+00 4.380e+00 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 1.860e+01 1.010e+02 2.800e+00 3.240e+00
  3.000e-01 2.810e+00 5.680e+00 1.030e+00 3.170e+00 1.185e+03]
 [1.437e+01 1.950e+00 2.500e+00 1.680e+01 1.130e+02 3.850e+00 3.490e+00
  2.400e-01 2.180e+00 7.800e+00 8.600e-01 3.450e+00 1.480e+03]
 [1.324e+01 2.590e+00 2.870e+00 2.100e+01 1.180e+02 2.800e+00 2.690e+00
  3.900e-01 1.820e+00 4.320e+00 1.040e+00 2.930e+00 7.350e+02]
 [1.420e+01 1.760e+00 2.450e+0

In [ ]:
#import the necessary module
from sklearn.model_selection import train_test_split

#split data set into train and test sets
data_train, data_test, target_train, target_test = train_test_split(X,y, test_size = 0.34, random_state = 114)

In [ ]:
import numpy as np
gnb = GaussianNB()

#Train the model using the training sets
gnb.fit(data_train, target_train)

#Predict the response for test dataset
target_pred = gnb.predict(data_test)
target_pred

array([1, 2, 0, 2, 1, 2, 1, 2, 1, 0, 2, 0, 2, 0, 0, 2, 0, 1, 2, 0, 1, 1,
       1, 2, 2, 1, 2, 1, 2, 0, 0, 1, 1, 2, 0, 0, 1, 0, 1, 0, 2, 0, 1, 1,
       0, 1, 0, 2, 1, 1, 1, 1, 0, 1, 2, 0, 0, 1, 0, 1, 0])

In [ ]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))

Accuracy: 0.9508196721311475


In [ ]:
#Import confusion_matrix from scikit-learn metrics module for confusion_matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test, target_pred)

array([[21,  1,  0],
       [ 0, 23,  2],
       [ 0,  0, 14]])

In [ ]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
precision = precision_score(target_test, target_pred, average=None)
recall = recall_score(target_test, target_pred, average=None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [1.         0.95833333 0.875     ]
recall: [0.95454545 0.92       1.        ]
